name       : python-nbformat
version    : 5.7.0
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/n/nbformat/nbformat-5.7.0.tar.gz : 1d4760c15c1a04269ef5caf375be8b98dd2f696e5eb9e603ec2bf091f9b0d3f3
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Reference implementation of the Jupyter Notebook format
description: |
    This package contains the base implementation of the Jupyter Notebook format, and Python APIs for working with notebooks.
builddeps  :
    - python-build
    - python-fastjsonschema # check
    - python-hatch-nodejs-version
    - python-installer
    - python-jsonschema     # check
    - python-jupyter_core   # check
    - python-pytest         # check
    - python-testpath       # check
rundeps    :
    - python-fastjsonschema
    - python-jsonschema
    - python-jupyter_core
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # Require python-pep440
#    %python3_test pytest3 -v
