name       : python-nbformat
version    : 5.0.7
release    : 4
source     :
    - https://github.com/jupyter/nbformat/archive/5.0.7.tar.gz : cecd87b9fa74ac47b322d0c692eb14955c157b6f22806b77d03c83b104bbd78c
license    : BSD-3-Clause
component  : programming.python
summary    : Reference implementation of the Jupyter Notebook format
description: |
    Reference implementation of the Jupyter Notebook format.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-jsonschema
    - python-traitlets
setup      : |
    %python3_setup
install    : |
    %python3_install
