name       : python-nbformat
version    : 5.1.3
release    : 7
source     :
    - https://github.com/jupyter/nbformat/archive/refs/tags/5.1.3.tar.gz : 437b72e20eaa76230cdfe48cf388551a1ebc5880e9251aa7f614dbc4680c9ea3
license    : BSD-3-Clause
component  : programming.python
summary    : Reference implementation of the Jupyter Notebook format
description: |
    Reference implementation of the Jupyter Notebook format.
builddeps  :
    - pkgconfig(python3)
    - python-ipython_genutils
    - python-jsonschema
    - python-jupyter_core
    - python-pytest # check
    - python-testpath # check
    - python-traitlets
rundeps    :
    - python-ipython_genutils
    - python-jupyter_core
    - python-jsonschema
    - python-traitlets
setup      : |
    # Remove fastjsonschema tests
    rm nbformat/tests/test_validator.py

    %python3_setup
install    : |
    %python3_install
check      : |
     %python3_test pytest3
