name       : python-nbformat
version    : 5.2.0
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/n/nbformat/nbformat-5.2.0.tar.gz : 93df0b9c67221d38fb970c48f6d361819a6c388299a0ef3171bbb912edfe1324
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Reference implementation of the Jupyter Notebook format
description: |
    This package contains the base implementation of the Jupyter Notebook format, and Python APIs for working with notebooks.
builddeps  :
    - python-jsonschema   # check
    - python-jupyter_core # check
    - python-pytest       # check
    - python-testpath     # check
rundeps    :
    - python-jsonschema
    - python-jupyter_core
setup      : |
    # Remove fastjsonschema tests
    rm tests/test_validator.py
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
