name       : python-nbformat
version    : 4.4.0
release    : 3
source     :
    - https://github.com/jupyter/nbformat/archive/4.4.0.tar.gz : cfa7b2dbb81ab7a64492f09f2cb65d69a1d009fe5d6e18ee7bb94446b114ede3
license    : BSD-3-Clause
component  : programming.python
summary    : Reference implementation of the Jupyter Notebook format.
description: |
    Reference implementation of the Jupyter Notebook format.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-ipython_genutils
    - python-jsonschema
    - python-jupyter_core
    - python-traitlets
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
